
export const ADD_NEW_BLOG_START = 'ADD_NEW_BLOG_START';
export const ADD_NEW_BLOG_SUCCESS = 'ADD_NEW_BLOG_SUCCESS';
export const ADD_NEW_BLOG_FAILED = 'ADD_NEW_BLOG_FAILED';

export const GET_ALL_BLOGS_START = 'GET_ALL_BLOGS_START';
export const GET_ALL_BLOGS_SUCCESS = 'GET_ALL_BLOGS_SUCCESS';
export const GET_ALL_BLOGS_FAILED = 'GET_ALL_BLOGS_FAILED';

export const UPDATE_BLOG_START = 'UPDATE_BLOG_START';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAILED = 'UPDATE_BLOG_FAILED';

export const DELETE_BLOG_START = 'DELETE_BLOG_START';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILED = 'DELETE_BLOG_FAILED';