
export const ADD_NEW_CASE_START = 'ADD_NEW_CASE_START';
export const ADD_NEW_CASE_SUCCESS = 'ADD_NEW_CASE_SUCCESS';
export const ADD_NEW_CASE_FAILED = 'ADD_NEW_CASE_FAILED';

export const GET_ALL_CASES_START = 'GET_ALL_CASES_START';
export const GET_ALL_CASES_SUCCESS = 'GET_ALL_CASES_SUCCESS';
export const GET_ALL_CASES_FAILED = 'GET_ALL_CASES_FAILED';

export const UPDATE_CASE_START = 'UPDATE_CASE_START';
export const UPDATE_CASE_SUCCESS = 'UPDATE_CASE_SUCCESS';
export const UPDATE_CASE_FAILED = 'UPDATE_CASE_FAILED';

export const DELETE_CASE_START = 'DELETE_CASE_START';
export const DELETE_CASE_SUCCESS = 'DELETE_CASE_SUCCESS';
export const DELETE_CASE_FAILED = 'DELETE_CASE_FAILED';