
export const ADD_NEW_DONATION_START = 'ADD_NEW_DONATION_START';
export const ADD_NEW_DONATION_SUCCESS = 'ADD_NEW_DONATION_SUCCESS';
export const ADD_NEW_DONATION_FAILED = 'ADD_NEW_DONATION_FAILED';

export const GET_ALL_DONATIONS_START = 'GET_ALL_DONATIONS_START';
export const GET_ALL_DONATIONS_SUCCESS = 'GET_ALL_DONATIONS_SUCCESS';
export const GET_ALL_DONATIONS_FAILED = 'GET_ALL_DONATIONS_FAILED';

export const UPDATE_DONATION_START = 'UPDATE_DONATION_START';
export const UPDATE_DONATION_SUCCESS = 'UPDATE_DONATION_SUCCESS';
export const UPDATE_DONATION_FAILED = 'UPDATE_DONATION_FAILED';

export const DELETE_DONATION_START = 'DELETE_DONATION_START';
export const DELETE_DONATION_SUCCESS = 'DELETE_DONATION_SUCCESS';
export const DELETE_DONATION_FAILED = 'DELETE_DONATION_FAILED';